var items ={
    Staters:[
        {
            itemname:'vegManchuria',
            itemprice:'900',
            quantity:1,
            quantityunits:'kg'
        },
        {
            itemname:'Panner tikka',
            itemprice:'1000',
            quantity:1,
            quantityunits:'kg'
            },
        {
            itemname:'Chilli Chicken',
            itemprice:'1200',
            quantity:1,
            quantityunits:'kg'
            },
        {
            itemname:'Babycorn',
            itemprice:'900',
            quantity:1,
            quantityunits:'kg'
            },
    ],
    Liquids:[
        {
            itemname:'Rasam',
            itemprice:'100',
            quantity:1,
            quantityunits:'liters'
        },
        {
            itemname:'Sambar',
            itemprice:'120',
            quantity:1,
            quantityunits:'liters'
        },
        {
            itemname:'Curd-rasam',
            itemprice:'200',
            quantity:1,
            quantityunits:'liters'
        },
        {
            itemname:'Curd',
            itemprice:'100',
            quantity:1,
            quantityunits:'liters'
        },
    ],
    Curries:[
        {
            itemname:'Panner-cashew',
            itemprice:'210',
            quantity:1,
            quantityunits:'kg'
        },
        {
            itemname:'Punukulu-mulakkada',
            itemprice:'180',
            quantity:1,
            quantityunits:'kg'
        },
        {
            itemname:'Chicken',
            itemprice:'300',
            quantity:1,
            quantityunits:'kg'
        },
        {
            itemname:'Dal-Tomoto',
            itemprice:'150',
            quantity:1,
            quantityunits:'kg'
        },
    ],
    Rice:[
        {
            itemname:'Pulihora',
            itemprice:'120',
            quantity:1,
            quantityunits:'kg'
        },
        {
        itemname:'Birayani',
        itemprice:'250',
        quantity:1,
        quantityunits:'kg'
        },
        {
            itemname:'White-rice',
            itemprice:'70',
            quantity:1,
            quantityunits:'kg'
        },
        {
            itemname:'Fried-rice',
            itemprice:'100',
            quantity:1,
            quantityunits:'kg'
        },
    ],
    Bread:[
        {
            itemname:'roti',
            itemprice:'60',
            quantity:1,
            quantityunits:'kg'
        },
        {
            itemname:'rumali',
            itemprice:'60',
            quantity:1,
            quantityunits:'kg'
        },
        {
            itemname:'nan',
            itemprice:'120',
            quantity:1,
            quantityunits:'kg'
        },
        {
            itemname:'Sandwich',
            itemprice:'100',
            quantity:1,
            quantityunits:'kg'
        },
    ]
}